# Generated by Django 6.0 on 2025-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
