# Generated by Django 6.0 on 2025-12-11 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_team_flag_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_confirmed', True)), fields=('tournament', 'selected_team'), name='unique_team_per_tournament_when_paid'),
        ),
    ]
