# Generated by Django 6.0 on 2025-12-11 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentregistration_unique_team_per_tournament_when_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_team_per_tournament_when_paid',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_confirmed', True)), fields=('tournament', 'selected_team', 'payment_confirmed'), name='unique_team_per_tournament'),
        ),
    ]
