# Generated by Django 6.0 on 2025-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_player',
            field=models.BooleanField(default=True),
        ),
    ]
